### ISSUE TITLE
Get someone to test examples/knitr-example .Rmd files

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/TTTworkshop#2]
Maybe @grinnellm , and someone new who hasn't built a document before.

**Comment by andrew-edwards** [comment]
So why would it let me assign that to @duplisea (not a member of pbs-assess)? Hmm... maybe he commented somewhere on this repo.

**Comment by grinnellm** [comment]
Worked for me (using RStudio).

**Comment by ricardd** [comment]
Also using RStudio, but I get an error after pushing "Knit":

"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS knitr-example.utf8.md --to latex --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output knitr-example.tex --template "C:\~\R\win-library\3.5\rmarkdown\rmd\latex\default-1.17.0.2.tex" --highlight-style tango --latex-engine pdflatex --variable graphics=yes --variable "geometry:margin=1in" --variable "compact-title:yes" --include-in-header "C:\Users\RicardD\AppData\Local\Temp\1\RtmpAFJN1l\rmarkdown-str1c201fc9690.html" 
output file: knitr-example.knit.md


Output created: knitr-example.pdf
Error in tools::file_path_as_absolute(output_file) : 
  file 'knitr-example.pdf' does not exist
Calls: <Anonymous> -> <Anonymous>
In addition: Warning message:
In readLines(logfile) : incomplete final line found on 'knitr-example.log'
Execution halted

**Comment by ricardd** [comment]
I completely uninstalled and reinstalled MiKTeX, and chose "install packages on the fly" in the install wizard. But I was still getting an error from MiKTeX ("Entry Point not Found" dll error).

The fix, as suggested by @cgrandin, was to start a console as administrator and invoke the following command:

initexmf --mklinks --force --admin

**Comment by ricardd** [comment]
Not trying to be a dictator here, but the solution for issue #29 also fixed my problem with compiling the PDF knitr examples, so I am closing this issue too.
