### ISSUE TITLE
Please confirm your middle initials (or lack of) for those people I couldn't easily find them (see list)

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/TTTworkshop#33]
As mentioned in the meeting (and in the spirit of collaboration), we're listing everyone as a co-author on the Proceedings. I couldn't (easily) find middle initials for the following people, please add them below as a comment or tick off your name if you don't have one. Thanks.

- [x] Erika Anderson
- [x] Brendan Connors
- [ ] Mathieu Desgagn\'{e}s
- [x] David Fishman
- [x] Cameron Freshwater
- [x] A. Rob Kronlund (yes?)
- [x] Daniel Ricard
- [ ] Bob Rogers
- [x] Mark Simpson
- [x] Laura Wheeland
- [x] Catarina Wor
- [x] Xinhua Zhu

@ErikaDAnderson @brendanmichaelconnors @mathieu-desgagnes @davjfish @CamFreshwater @ricardd @catarinawor

**Comment by CamFreshwater** [comment]
I don't use one

**Comment by davjfish** [comment]
David J. Fishman.. Thanks!

**Comment by ErikaDAnderson** [comment]
I use Erika D Anderson.
Thanks –the workshop was really useful.

**Comment by catarinawor** [comment]
I'm not sure if I deserve to be an author. =)

**Comment by andrew-edwards** [comment]
Thanks. Sorry, the checkboxes don't seem to be checkable by everyone (maybe you have to be a pbs-assess person?) so just reply here. Brendan, I have yours now.

**Comment by zhujeff** [comment]
I don't use one. Thanks!

**Comment by ricardd** [comment]
No initials for me.

**Comment by grinnellm** [comment]
Did Ann write a blurb? If so, we should include her too.

**Comment by andrew-edwards** [comment]
@grinnellm - good thought. I think someone else wrote it, but I'll double check.

**Comment by andrew-edwards** [comment]
Am fairly sure Bob and Mathieu don't have middle initials, so closing.
