### ISSUE TITLE
Are you planning to keep editing today?

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/TTTworkshop#34]
@duplisea @grinnellm  I printed out yesterday's version and was about to read through (having messed about with names yesterday afternoon), but it's already out of date (ha ha).

Just wondering what your plans are for working on it today. I want to do a big read through and some editing, though you've both helpfully been doing some.

**Comment by grinnellm** [comment]
I can leave it alone for the rest of today, no problem.

**Comment by andrew-edwards** [comment]
Fine if you're working on it (sorry if my question came across wrong). I only really have today and it keeps changing, making it a little inefficient. 

Now @seananderson  is editing!! Ha ha. I plan to do lots of editing today, and I'll send out a copy to everyone anyway. Let me know if you want to keep at it until, say, lunch, and then I can work on it.

**Comment by grinnellm** [comment]
Are you saying "STOP COLLABORATING!"? :)
I'm fine with leaving it in your hands until you're done, @andrew-edwards .

**Comment by seananderson** [comment]
As long as individual sentences are on individual lines it's usually not too bad in terms of conflicts and they are easy to resolve. For heavily edited multi-author text I've found that breaking on even shorter phrases has worked well. E.g. https://raw.githubusercontent.com/ss3sim/ss3sim/82622d66a25050c868f9ac27f779b218baa64783/inst/ms/ss3sim-ms.md

Anyways, that's just an aside. I'm done for now. Go at it.

**Comment by andrew-edwards** [comment]
Thanks. I'm actually finding it quite amusing (Matt said he was done, and Dan was quiet for a while, but then it still kept changing!). Given it's a small document (rather than code), it's more the inefficiencies of everyone doing similar things - I just want to read through and make it consistent. 

Loving the enthusiasm though!

**Comment by ricardd** [comment]
Let me know when you are satisfied with the English abstract and I will translate it again (issue #36).

**Comment by andrew-edwards** [comment]
Okay, I've done some editing. Great if anyone can take a read through. Be good to be able to email out the .pdf to participants at the end of day tomorrow, and give them, say, a week to reply with any major edits. I'll also submit for approval. 
If someone wants to read through the abstract again then Dan can re-translate - thanks!

**Comment by duplisea** [comment]
oops, I may have done this out of sequence. Sorry, just coming to terms with assignments. It is a great way to work though. I am sold.

**Comment by andrew-edwards** [comment]
1. I was thinking of adding some explicit references in that I mentioned in my talk (to demonstrate examples of using this stuff) - Pacific Herring (@grinnellm - which would be best, recent Res Doc or upcoming SR, please supply the details), Pacific Cod Res Doc (under revision), gfsynopsis (under revisions), Pacific Hake. 
Proves that we're just not making stuff up about how these tools are useful!

2. Will also move Dan R into the early list of co-authors. Are others planning on editing more? If so just make a note here so we know who's doing what.

3. I think it's looking good. Great collaborative effort.
How about I send out the version to participants (and for local sign off here) at 3:30PST? Give people a week for comments.

4. And I'll put in the middle initials that I've got so far (some by email).

**Comment by grinnellm** [comment]
Do you mind if I work on a function to format names for the citation, `trAuthsBack`?

**Comment by grinnellm** [comment]
Done!

**Comment by andrew-edwards** [comment]
Okay, I'll email out shortly.
