### ISSUE TITLE
Font looks too big on cover page

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/TTTworkshop#35]
@grinnellm  - compared to the 2016 one I sent you. Shouldn't it be Arial (or whatever) and smaller? The inside cover page looks perfect. 
I don't want to mess up your style file (any more..., ha ha).

**Comment by grinnellm** [comment]
I have 'published' two tech reports using this style file, so it should be OK. Though, looking at it now with the long title and very long author list, reducing the font might be a good idea. There's pretty minimal checking for tech reports (used to be Bev, but I'm not sure who does it now). I also don't mind changing the font..

**Comment by andrew-edwards** [comment]
Good to know. Just looks a bit big, but partly due to so much text. If you want to have a go that'd be great.
Yes, it was Bev who checked stuff, but I think there is minimal checking now. Good to know your one got through okay.

**Comment by seananderson** [comment]
If we can get away with the current Computer Modern font, which I think we can, I would very much prefer this to Arial/Helvetica! If only, some day, we could convince them to let us use it with Research Documents...

**Comment by grinnellm** [comment]
I reduced some of the font on the first page; now it's all `Large` (the title and bottom two lines "Canadian Technical Report of Fisheries and Aquatic Sciences NNNN", used to be `LARGE`). I can make it smaller if you'd like?

**Comment by andrew-edwards** [comment]
Sean - yes, I'm just talking about the cover page (which I presume has to conform to some standards). Agree, I hate the other ones for the main text.

**Comment by grinnellm** [comment]
I think `large` is too small (at least, its smaller than other Tech Reports that I've seen). Maybe go back to `Large`?

**Comment by duplisea** [comment]
agree, the large font is better than the small

**Comment by andrew-edwards** [comment]
large looks the same as the EA workshop one (and the others I've seen). Think I prefer that, but will go with the majority..... (currently 2-1 to Large!). 

Maybe they're just not so strict now on the rules (thankfully). No big deal.

**Comment by grinnellm** [comment]
This is what I have on the cover of my last (2012!) Tech Report with LaTeX:
![image](https://user-images.githubusercontent.com/25674027/49532227-e6fa7780-f870-11e8-850e-4402f539699a.png)

**Comment by andrew-edwards** [comment]
Aren't the author names there a bit smaller than the title (which looks good)? I'm thinking the current one is all the same size, which is a bit much with so many authors.

**Comment by grinnellm** [comment]
Yes, this one the title is `LARGE` and the authors are `Large`. How about we do Title (and last two lines "Canadian Technical...") in `Large`, and the rest `large`? I just tried it, that looks good (yay compromise!):
![image](https://user-images.githubusercontent.com/25674027/49532986-a7cd2600-f872-11e8-8d47-46ef8517b190.png)
