### ISSUE TITLE
Abstract will need translating again

### ISSUE THREAD

**Issue by andrew-edwards** [pbs-assess/TTTworkshop#36]

**Comment by andrew-edwards** [comment]
On the ball Dan! No rush - wait until someone else has read it, including @duplisea . I put in mention of the Nfld survey report and of rosettafish, to show that we actually got some tangible products out of the workshop.

**Comment by andrew-edwards** [comment]
@ricardd While you're there and looking for something to translate ;), could you please just do the title. I've updated it to (for consistency with previous TESA procs):

```
Proceedings of the Technical Expertise in Stock Assessment
 (TESA) national workshop on 'Tools for transparent, traceable, and transferable
 assessments', 27-30 November 2018, Nanaimo, British Columbia
```
Thanks - I just need it for the form to request a publication number.

**Comment by ricardd** [comment]
It would go something like this:

```
Compte rendu du groupe de travail national d'Expertise Technique en Évaluation 
des Stocks (ETES) sur les "Méthodes pour des évaluations transparentes, 
traçables et transférables", 27-30 novembre 2018, Nanaimo, Colombie-Britanique.
```

**Comment by ricardd** [comment]
Why didn't my last commit close this issue automatically?

https://help.github.com/articles/closing-issues-using-keywords/
