### ISSUE TITLE
URL links for 'Termium Plus' and 'DFO Bilingual Lexicon' are the same

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/TTTworkshop#38]
See Section 4.2.2 (Translation databases).

**Comment by ricardd** [comment]
Why didn't my last commit close this issue automatically?

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by grinnellm** [comment]
From git, it looks like you have to put one of these, followed by the issue number:
close, closes, closed, fix, fixes, fixed, resolve, resolves, resolved
i.e., `close # xx`

**Comment by grinnellm** [comment]
Thanks for fixing it, either way:)

**Comment by ricardd** [comment]
Oh, I see now, I should've written "resolves #38" instead of "resolves issue #38".
