### ISSUE TITLE
Add 'pages' to book citations

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/TTTworkshop#40]
The example for books referenced by Tech Reports is:
Ward, J.V. 1992. Aquatic insect ecology V.1: biology and habitat. Wiley & Sons, New York. 438 p.
I'm not sure how to get the number of pages to appear. I did try to add it to the `notes` item in the bib reference, but that didn't work.

**Comment by andrew-edwards** [comment]
Yes, doesn't look obvious (I don't know .csl). I like them in but no big deal - I had a journal take them out recently anyway. I think we had them for `resdoc.bst`, so that might help (though this is .csl now).

**Comment by seananderson** [comment]
I don't really know csl either, but it's not too hard to wade through or to use an editor like http://editor.citationstyles.org/about/ or I think there is one built into Mendeley.

**Comment by grinnellm** [comment]
I'm not familiar with csl, and didn't see anything obvious when I opened csas.csl. So, I'm fine with leaving it as is for now, but we may have to update this for res docs and science responses.
